-- Run as SECURITYADMIN/SYSADMIN. Idempotent bootstrap of the delivery target.
CREATE ROLE IF NOT EXISTS LAKEHOUSE_LOADER;
CREATE WAREHOUSE IF NOT EXISTS LOAD_WH
    WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS LAKEHOUSE;
CREATE SCHEMA IF NOT EXISTS LAKEHOUSE.GOLD;

GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE LAKEHOUSE_LOADER;
GRANT USAGE ON DATABASE LAKEHOUSE TO ROLE LAKEHOUSE_LOADER;
GRANT USAGE, CREATE TABLE ON SCHEMA LAKEHOUSE.GOLD TO ROLE LAKEHOUSE_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA LAKEHOUSE.GOLD TO ROLE LAKEHOUSE_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LAKEHOUSE.GOLD TO ROLE LAKEHOUSE_LOADER;
