USE SCHEMA LAKEHOUSE.GOLD;

CREATE TABLE IF NOT EXISTS GOLD_REVIEWS_DAILY (
    REVIEW_DATE   DATE,
    PRODUCT_ID    VARCHAR,
    REVIEW_COUNT  NUMBER,
    AVG_SCORE     FLOAT,
    POSITIVES     NUMBER,
    NEGATIVES     NUMBER,
    AVG_TEXT_LEN  FLOAT,
    CONSTRAINT PK_REVIEWS_DAILY PRIMARY KEY (REVIEW_DATE, PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS GOLD_SUBREDDIT_ENGAGEMENT (
    CREATED_DATE     DATE,
    SUBREDDIT        VARCHAR,
    POSTS            NUMBER,
    AVG_SCORE        FLOAT,
    AVG_COMMENTS     FLOAT,
    AVG_UPVOTE_RATIO FLOAT,
    ENGAGED_POSTS    NUMBER,
    CONSTRAINT PK_SUBREDDIT_ENGAGEMENT PRIMARY KEY (CREATED_DATE, SUBREDDIT)
);

CREATE TABLE IF NOT EXISTS GOLD_ORDERS_ENRICHED (
    ORDER_ID    NUMBER,
    CUSTOMER_ID NUMBER,
    FULL_NAME   VARCHAR,
    SEGMENT     VARCHAR,
    COUNTRY     VARCHAR,
    STATUS      VARCHAR,
    AMOUNT      NUMBER(12,2),
    CURRENCY    VARCHAR,
    UPDATED_AT  TIMESTAMP_NTZ,
    ORDER_DATE  DATE,
    CONSTRAINT PK_ORDERS_ENRICHED PRIMARY KEY (ORDER_ID)
);
